name: joiner_app_walkthrough
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  custom_lint: ^0.6.0
  flutter:
    sdk: flutter
  go_router: ^12.1.3
  go_router_builder: ^2.4.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
